import { useState, useEffect } from "react";
import "./Ticker.css";

export function Ticker() {
  const [ticker, setTicker] = useState("");

  useEffect(() => {
    const handlePywebviewReady = () => {
      // @ts-expect-error TS2339: Property 'pywebview' does not exist on type 'Window & typeof globalThis'.
      if (!window.pywebview.state) {
        // @ts-expect-error TS2339: Property 'pywebview' does not exist on type 'Window & typeof globalThis'.
        window.pywebview.state = {};
      }

      // Expose setTicker in order to call it from Python
      // @ts-expect-error TS2339: Property 'pywebview' does not exist on type 'Window & typeof globalThis'.
      window.pywebview.state.setTicker = setTicker;
    };

    // Check if pywebview is already ready
    // @ts-expect-error TS2339: Property 'pywebview' does not exist on type 'Window & typeof globalThis'.
    if (window.pywebview) {
      handlePywebviewReady();
    } else {
      window.addEventListener("pywebviewready", handlePywebviewReady);
    }

    // Cleanup event listener on component unmount
    return () => {
      window.removeEventListener("pywebviewready", handlePywebviewReady);
    };
  }, []);

  return (
    <div className="ticker-container">
      <h1>Welcome to pywebview!</h1>

      <em>
        You can freely communicate between Javascript with Python without a HTTP
        server. This value, for example, is being generated by Python code:
      </em>
      <strong>{ticker}</strong>
    </div>
  );
}
